version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - media:/media
    env_file:
      - .env
    build:
      context: .
    ports:
    - "8000:8000"

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/static
      - media:/media
    ports:
      - 80:80
    depends_on:
      - django_gunicorn

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - "/var/lib/letsencrypt:/var/lib/letsencrypt"
  #     - "/etc/letsencrypt:/etc/letsencrypt"
  #   command: certbot --nginx -d api.psd2htmlx.com -d www.api.psd2htmlx.com
volumes:
  static:
  media: